apiVersion: apps/v1
kind: Deployment
metadata:
  name: tal-px-message-push-deployment
  labels:
    app: tal-px-message-push
spec:
  # 副本数
  replicas: 1
  selector:
    matchLabels:
      app: tal-px-message-push
  template:
    metadata:
      labels:
        app: tal-px-message-push
    spec:
      containers:
      - name: tal-px-message-push
        image: tal-px-message-push:0.0.1
        workingDir: /usr/tal-px-message-push
        command: ["/bin/bash", "-c", "java -Xms512m -Xmx512m -Dspring.profiles.active=integrated -Djava.security.egd=file:/dev/./urandom -jar app.jar"]
        ports:
        - containerPort: 9340
#        volumeMounts:
#        - mountPath: /script/logs
#          name: logs
#      volumes:
#      - name: logs
#        configMap:
#          name: tal-px-message-push-logs
#          items:
#          - key: logs
#            path: /opt/tal/tal-px-message-push/logs