apiVersion: v1
kind: Service
metadata:
  name: tal-px-message-push-service
  labels:
    app: tal-px-message-push
spec:
  type: NodePort
  ports:
  - port: 9340
    protocol: TCP
    targetPort: 9340
  selector:
    app: tal-px-message-push