
spring:
  thymeleaf:
    enabled: true
    prefix: classpath:templates/
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/



host: localhost:8806

filePath: /Users/wdke/person/java-code/github/wdk-code-general-core-test/