eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://192.168.1.101:8802/eureka/

spring:
  thymeleaf:
    enabled: true
    prefix: classpath:templates/
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

  #数据库连接配置开始
  datasource:
    url: jdbc:mysql://192.168.1.99:3306/wdk_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true


#mybatis配置开始
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.wdk.general.core.storage.entity
  mapper-locations: classpath:mapper/*.xml
#mybatis配置结束


#分页拦截器配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#分页拦截器配置结束



host: localhost:8806

filePath: /Users/wdke/person/java-code/auto-code/
staticFile: /Users/wdke/person/java-code/github/wdk-code-general/wdk-code-general-core/src/main/resources/static
